In [12]:
import pandas as pd

In [13]:
# 1. Carga del dataset
df_stablecoin = pd.read_csv(r'stablecoins_analisis.csv')
# 2. Visualizar las primeras 5 filas
print("--- Primeras filas del dataset ---")
display(df_stablecoin.head())

# 3. Inspección de tipos de datos y valores no nulos
print("\n--- Información general del DataFrame ---")
df_stablecoin.info()

--- Primeras filas del dataset ---

        fecha  supply_stablecoin  precio_moneda  desviacion_peg
0  2017-11-29           109970.0       1.001228        0.001228
1  2017-11-30           109970.0       1.001228        0.001228
2  2017-12-01           109970.0       1.001228        0.001228
3  2017-12-02           109970.0       1.001228        0.001228
4  2017-12-03           109970.0       1.001228        0.001228

--- Información general del DataFrame ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3140 entries, 0 to 3139
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   fecha              3140 non-null   object
 1   supply_stablecoin  3140 non-null   float64
 2   precio_moneda      3140 non-null   float64
 3   desviacion_peg     3140 non-null   float64
dtypes: float64(3), object(1)
memory usage: 98.2+ KB

In [14]:
# 1. Carga del dataset
df_cripto = pd.read_csv(r'data_bitcoin.csv')
# 2. Visualizar las primeras 5 filas
print("--- Primeras filas del dataset ---")
display(df_cripto.head())

# 3. Inspección de tipos de datos y valores no nulos
print("\n--- Información general del DataFrame ---")
df_cripto.info()

--- Primeras filas del dataset ---

        fecha  precio_bitcoin
0  2025-07-05   108040.891940
1  2025-07-06   108217.468500
2  2025-07-07   109215.197718
3  2025-07-08   108300.716758
4  2025-07-09   108953.191877

--- Información general del DataFrame ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   fecha           365 non-null    object
 1   precio_bitcoin  365 non-null    float64
dtypes: float64(1), object(1)
memory usage: 5.8+ KB

In [17]:
# 1. Carga del dataset
df_consolidado = pd.read_csv(r'criptoradar_dataset_final.csv')
# 2. Visualizar las primeras 5 filas
print("--- Primeras filas del dataset ---")
display(df_consolidado.head())

# 3. Inspección de tipos de datos y valores no nulos
print("\n--- Información general del DataFrame ---")
df_consolidado.info()

--- Primeras filas del dataset ---

,fecha,precio_crypto,crypto_id,supply_stablecoin,precio_moneda,desviacion_peg
0,2025-07-05,108040.891940,bitcoin,1.594788e+11,1.000000,0.000000
1,2025-07-06,108217.468500,bitcoin,1.594788e+11,1.000000,0.000000
2,2025-07-07,109215.197718,bitcoin,1.594638e+11,0.999955,0.000045
3,2025-07-08,108300.716758,bitcoin,1.595207e+11,1.000000,0.000000
4,2025-07-09,108953.191877,bitcoin,1.594557e+11,1.000000,0.000000

--- Información general del DataFrame ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   fecha              1825 non-null   object
 1   precio_crypto      1825 non-null   float64
 2   crypto_id          1825 non-null   object
 3   supply_stablecoin  1825 non-null   float64
 4   precio_moneda      1825 non-null   float64
 5   desviacion_peg     1825 non-null   float64
dtypes: float64(4), object(2)
memory usage: 85.7+ KB

In [23]:
print("--- Correlación entre el Supply de la Stablecoin y cada Criptomoneda ---")

# Agrupamos por cada moneda y calculamos la correlación interna de sus columnas
correlaciones_por_crypto = df_consolidado.groupby('crypto_id').apply(
    lambda x: x['supply_stablecoin'].corr(x['precio_crypto'])
)

display(correlaciones_por_crypto)

--- Correlación entre el Supply de la Stablecoin y cada Criptomoneda ---

/var/folders/pq/7bx4chp93qg2ck6vkzg024800000gn/T/ipykernel_1979/1262586970.py:4: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  correlaciones_por_crypto = df_consolidado.groupby('crypto_id').apply(

crypto_id
binancecoin   -0.203903
bitcoin       -0.745581
ethereum      -0.629285
ripple        -0.805014
solana        -0.688422
dtype: float64

Al ser un numero entre -0.4 y -0.9.Se demuestra con datos reales de 1 año que cuando el precio de Bitcoin baja, el suministro de stablecoins sube (los inversores buscan refugio)y eso se ve reflejado en el aumento de precio de supply.