In [2]:
import pandas as pd

In [7]:
# 1. Carga del dataset
df = pd.read_csv(r'stablecoins_analisis.csv')
# 2. Visualizar las primeras 5 filas
print("--- Primeras filas del dataset ---")
display(df.head())

# 3. Inspección de tipos de datos y valores no nulos
print("\n--- Información general del DataFrame ---")
df.info()

--- Primeras filas del dataset ---

        fecha  supply_stablecoin  precio_moneda  desviacion_peg
0  2017-11-29           109970.0       1.001228        0.001228
1  2017-11-30           109970.0       1.001228        0.001228
2  2017-12-01           109970.0       1.001228        0.001228
3  2017-12-02           109970.0       1.001228        0.001228
4  2017-12-03           109970.0       1.001228        0.001228

--- Información general del DataFrame ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3139 entries, 0 to 3138
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   fecha              3139 non-null   object
 1   supply_stablecoin  3139 non-null   float64
 2   precio_moneda      3139 non-null   float64
 3   desviacion_peg     3139 non-null   float64
dtypes: float64(3), object(1)
memory usage: 98.2+ KB

In [4]:
# 1. Carga del dataset
df = pd.read_csv(r'data_bitcoin.csv')
# 2. Visualizar las primeras 5 filas
print("--- Primeras filas del dataset ---")
display(df.head())

# 3. Inspección de tipos de datos y valores no nulos
print("\n--- Información general del DataFrame ---")
df.info()

--- Primeras filas del dataset ---

        fecha  precio_bitcoin
0  2026-01-05    91373.215881
1  2026-01-06    93926.795649
2  2026-01-07    93666.863873
3  2026-01-08    91257.155440
4  2026-01-09    90983.515781

--- Información general del DataFrame ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181 entries, 0 to 180
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   fecha           181 non-null    object
 1   precio_bitcoin  181 non-null    float64
dtypes: float64(1), object(1)
memory usage: 3.0+ KB

In [5]:
# 1. Carga del dataset
df = pd.read_csv(r'criptoradar_dataset_final.csv')
# 2. Visualizar las primeras 5 filas
print("--- Primeras filas del dataset ---")
display(df.head())

# 3. Inspección de tipos de datos y valores no nulos
print("\n--- Información general del DataFrame ---")
df.info()

--- Primeras filas del dataset ---

        fecha  precio_bitcoin       suministro_stablecoins
0  2026-01-05    91373.215881  {'peggedUSD': 187083832369}
1  2026-01-06    93926.795649  {'peggedUSD': 187293532611}
2  2026-01-07    93666.863873  {'peggedUSD': 187067881365}
3  2026-01-08    91257.155440  {'peggedUSD': 187068870349}
4  2026-01-09    90983.515781  {'peggedUSD': 186177870330}

--- Información general del DataFrame ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181 entries, 0 to 180
Data columns (total 3 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   fecha                   181 non-null    object
 1   precio_bitcoin          181 non-null    float64
 2   suministro_stablecoins  181 non-null    object
dtypes: float64(1), object(2)
memory usage: 4.4+ KB